
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.armure.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.armure.item.SandSwordItem;
import net.mcreator.armure.item.SandShovelItem;
import net.mcreator.armure.item.SandPickaxeItem;
import net.mcreator.armure.item.SandHoeItem;
import net.mcreator.armure.item.SandAxeItem;
import net.mcreator.armure.item.SandArmorItem;
import net.mcreator.armure.item.PierreArmorItem;
import net.mcreator.armure.item.OpaleSwordItem;
import net.mcreator.armure.item.OpaleShovelItem;
import net.mcreator.armure.item.OpalePickaxeItem;
import net.mcreator.armure.item.OpaleHoeItem;
import net.mcreator.armure.item.OpaleDustItem;
import net.mcreator.armure.item.OpaleAxeItem;
import net.mcreator.armure.item.OpaleArmorItem;
import net.mcreator.armure.item.NulleSwordItem;
import net.mcreator.armure.item.NulleShovelItem;
import net.mcreator.armure.item.NullePickaxeItem;
import net.mcreator.armure.item.NulleItem;
import net.mcreator.armure.item.NulleHoeItem;
import net.mcreator.armure.item.NulleAxeItem;
import net.mcreator.armure.item.NulleArmorItem;
import net.mcreator.armure.item.NoireSwordItem;
import net.mcreator.armure.item.NoireShovelItem;
import net.mcreator.armure.item.NoirePickaxeItem;
import net.mcreator.armure.item.NoireItem;
import net.mcreator.armure.item.NoireHoeItem;
import net.mcreator.armure.item.NoireAxeItem;
import net.mcreator.armure.item.NoireArmorItem;
import net.mcreator.armure.item.NimportearmureItem;
import net.mcreator.armure.item.Nimporte_outilsSwordItem;
import net.mcreator.armure.item.Nimporte_outilsShovelItem;
import net.mcreator.armure.item.Nimporte_outilsPickaxeItem;
import net.mcreator.armure.item.Nimporte_outilsHoeItem;
import net.mcreator.armure.item.Nimporte_outilsAxeItem;
import net.mcreator.armure.item.GrisSwordItem;
import net.mcreator.armure.item.GrisShovelItem;
import net.mcreator.armure.item.GrisPickaxeItem;
import net.mcreator.armure.item.GrisIngotItem;
import net.mcreator.armure.item.GrisHoeItem;
import net.mcreator.armure.item.GrisAxeItem;
import net.mcreator.armure.item.GrisArmorItem;
import net.mcreator.armure.item.DiamantItem;
import net.mcreator.armure.item.CuivreSwordItem;
import net.mcreator.armure.item.CuivreShovelItem;
import net.mcreator.armure.item.CuivrePickaxeItem;
import net.mcreator.armure.item.CuivreHoeItem;
import net.mcreator.armure.item.CuivreAxeItem;
import net.mcreator.armure.item.CuivreArmorItem;
import net.mcreator.armure.item.CacaSwordItem;
import net.mcreator.armure.item.CacaShovelItem;
import net.mcreator.armure.item.CacaPickaxeItem;
import net.mcreator.armure.item.CacaItem;
import net.mcreator.armure.item.CacaHoeItem;
import net.mcreator.armure.item.CacaAxeItem;
import net.mcreator.armure.item.CacaArmorItem;
import net.mcreator.armure.item.BlancSwordItem;
import net.mcreator.armure.item.BlancShovelItem;
import net.mcreator.armure.item.BlancPickaxeItem;
import net.mcreator.armure.item.BlancItem;
import net.mcreator.armure.item.BlancHoeItem;
import net.mcreator.armure.item.BlancAxeItem;
import net.mcreator.armure.item.BlancArmorItem;
import net.mcreator.armure.ArmureMod;

public class ArmureModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ArmureMod.MODID);
	public static final RegistryObject<Item> DIAMANT = REGISTRY.register("diamant", () -> new DiamantItem());
	public static final RegistryObject<Item> NIMPORTEBLOCK = block(ArmureModBlocks.NIMPORTEBLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NIMPORTEARMURE_HELMET = REGISTRY.register("nimportearmure_helmet", () -> new NimportearmureItem.Helmet());
	public static final RegistryObject<Item> NIMPORTEARMURE_CHESTPLATE = REGISTRY.register("nimportearmure_chestplate", () -> new NimportearmureItem.Chestplate());
	public static final RegistryObject<Item> NIMPORTEARMURE_LEGGINGS = REGISTRY.register("nimportearmure_leggings", () -> new NimportearmureItem.Leggings());
	public static final RegistryObject<Item> NIMPORTEARMURE_BOOTS = REGISTRY.register("nimportearmure_boots", () -> new NimportearmureItem.Boots());
	public static final RegistryObject<Item> BLOCKCACA = block(ArmureModBlocks.BLOCKCACA, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NIMPORTE_OUTILS_AXE = REGISTRY.register("nimporte_outils_axe", () -> new Nimporte_outilsAxeItem());
	public static final RegistryObject<Item> NIMPORTE_OUTILS_PICKAXE = REGISTRY.register("nimporte_outils_pickaxe", () -> new Nimporte_outilsPickaxeItem());
	public static final RegistryObject<Item> NIMPORTE_OUTILS_SWORD = REGISTRY.register("nimporte_outils_sword", () -> new Nimporte_outilsSwordItem());
	public static final RegistryObject<Item> NIMPORTE_OUTILS_SHOVEL = REGISTRY.register("nimporte_outils_shovel", () -> new Nimporte_outilsShovelItem());
	public static final RegistryObject<Item> NIMPORTE_OUTILS_HOE = REGISTRY.register("nimporte_outils_hoe", () -> new Nimporte_outilsHoeItem());
	public static final RegistryObject<Item> CACA_ARMOR_HELMET = REGISTRY.register("caca_armor_helmet", () -> new CacaArmorItem.Helmet());
	public static final RegistryObject<Item> CACA_ARMOR_CHESTPLATE = REGISTRY.register("caca_armor_chestplate", () -> new CacaArmorItem.Chestplate());
	public static final RegistryObject<Item> CACA_ARMOR_LEGGINGS = REGISTRY.register("caca_armor_leggings", () -> new CacaArmorItem.Leggings());
	public static final RegistryObject<Item> CACA_ARMOR_BOOTS = REGISTRY.register("caca_armor_boots", () -> new CacaArmorItem.Boots());
	public static final RegistryObject<Item> CACA_ORE = block(ArmureModBlocks.CACA_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CACA_BLOCK = block(ArmureModBlocks.CACA_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CASANDRA_WOOD = block(ArmureModBlocks.CASANDRA_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CASANDRA_LOG = block(ArmureModBlocks.CASANDRA_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CASANDRA_PLANKS = block(ArmureModBlocks.CASANDRA_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CASANDRA_LEAVES = block(ArmureModBlocks.CASANDRA_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CASANDRA_STAIRS = block(ArmureModBlocks.CASANDRA_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CASANDRA_SLAB = block(ArmureModBlocks.CASANDRA_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CASANDRA_FENCE = block(ArmureModBlocks.CASANDRA_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CASANDRA_FENCE_GATE = block(ArmureModBlocks.CASANDRA_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> CASANDRA_PRESSURE_PLATE = block(ArmureModBlocks.CASANDRA_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> CASANDRA_BUTTON = block(ArmureModBlocks.CASANDRA_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CACA_BOIS_WOOD = block(ArmureModBlocks.CACA_BOIS_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CACA_BOIS_LOG = block(ArmureModBlocks.CACA_BOIS_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CACA_BOIS_PLANKS = block(ArmureModBlocks.CACA_BOIS_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CACA_BOIS_LEAVES = block(ArmureModBlocks.CACA_BOIS_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CACA_BOIS_STAIRS = block(ArmureModBlocks.CACA_BOIS_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CACA_BOIS_SLAB = block(ArmureModBlocks.CACA_BOIS_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CACA_BOIS_FENCE = block(ArmureModBlocks.CACA_BOIS_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CACA_BOIS_FENCE_GATE = block(ArmureModBlocks.CACA_BOIS_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> CACA_BOIS_PRESSURE_PLATE = block(ArmureModBlocks.CACA_BOIS_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> CACA_BOIS_BUTTON = block(ArmureModBlocks.CACA_BOIS_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CACA_PICKAXE = REGISTRY.register("caca_pickaxe", () -> new CacaPickaxeItem());
	public static final RegistryObject<Item> CACA_AXE = REGISTRY.register("caca_axe", () -> new CacaAxeItem());
	public static final RegistryObject<Item> CACA_SWORD = REGISTRY.register("caca_sword", () -> new CacaSwordItem());
	public static final RegistryObject<Item> CACA_SHOVEL = REGISTRY.register("caca_shovel", () -> new CacaShovelItem());
	public static final RegistryObject<Item> CACA_HOE = REGISTRY.register("caca_hoe", () -> new CacaHoeItem());
	public static final RegistryObject<Item> CACA = REGISTRY.register("caca", () -> new CacaItem());
	public static final RegistryObject<Item> SAND_ARMOR_HELMET = REGISTRY.register("sand_armor_helmet", () -> new SandArmorItem.Helmet());
	public static final RegistryObject<Item> SAND_ARMOR_CHESTPLATE = REGISTRY.register("sand_armor_chestplate", () -> new SandArmorItem.Chestplate());
	public static final RegistryObject<Item> SAND_ARMOR_LEGGINGS = REGISTRY.register("sand_armor_leggings", () -> new SandArmorItem.Leggings());
	public static final RegistryObject<Item> SAND_ARMOR_BOOTS = REGISTRY.register("sand_armor_boots", () -> new SandArmorItem.Boots());
	public static final RegistryObject<Item> PIERRE_ARMOR_HELMET = REGISTRY.register("pierre_armor_helmet", () -> new PierreArmorItem.Helmet());
	public static final RegistryObject<Item> PIERRE_ARMOR_CHESTPLATE = REGISTRY.register("pierre_armor_chestplate", () -> new PierreArmorItem.Chestplate());
	public static final RegistryObject<Item> PIERRE_ARMOR_LEGGINGS = REGISTRY.register("pierre_armor_leggings", () -> new PierreArmorItem.Leggings());
	public static final RegistryObject<Item> PIERRE_ARMOR_BOOTS = REGISTRY.register("pierre_armor_boots", () -> new PierreArmorItem.Boots());
	public static final RegistryObject<Item> CUIVRE_ARMOR_HELMET = REGISTRY.register("cuivre_armor_helmet", () -> new CuivreArmorItem.Helmet());
	public static final RegistryObject<Item> CUIVRE_ARMOR_CHESTPLATE = REGISTRY.register("cuivre_armor_chestplate", () -> new CuivreArmorItem.Chestplate());
	public static final RegistryObject<Item> CUIVRE_ARMOR_LEGGINGS = REGISTRY.register("cuivre_armor_leggings", () -> new CuivreArmorItem.Leggings());
	public static final RegistryObject<Item> CUIVRE_ARMOR_BOOTS = REGISTRY.register("cuivre_armor_boots", () -> new CuivreArmorItem.Boots());
	public static final RegistryObject<Item> NULLE_ARMOR_HELMET = REGISTRY.register("nulle_armor_helmet", () -> new NulleArmorItem.Helmet());
	public static final RegistryObject<Item> NULLE_ARMOR_CHESTPLATE = REGISTRY.register("nulle_armor_chestplate", () -> new NulleArmorItem.Chestplate());
	public static final RegistryObject<Item> NULLE_ARMOR_LEGGINGS = REGISTRY.register("nulle_armor_leggings", () -> new NulleArmorItem.Leggings());
	public static final RegistryObject<Item> NULLE_ARMOR_BOOTS = REGISTRY.register("nulle_armor_boots", () -> new NulleArmorItem.Boots());
	public static final RegistryObject<Item> NOIRE_ARMOR_HELMET = REGISTRY.register("noire_armor_helmet", () -> new NoireArmorItem.Helmet());
	public static final RegistryObject<Item> NOIRE_ARMOR_CHESTPLATE = REGISTRY.register("noire_armor_chestplate", () -> new NoireArmorItem.Chestplate());
	public static final RegistryObject<Item> NOIRE_ARMOR_LEGGINGS = REGISTRY.register("noire_armor_leggings", () -> new NoireArmorItem.Leggings());
	public static final RegistryObject<Item> NOIRE_ARMOR_BOOTS = REGISTRY.register("noire_armor_boots", () -> new NoireArmorItem.Boots());
	public static final RegistryObject<Item> PIERRE_WOOD = block(ArmureModBlocks.PIERRE_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PIERRE_LOG = block(ArmureModBlocks.PIERRE_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PIERRE_PLANKS = block(ArmureModBlocks.PIERRE_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PIERRE_LEAVES = block(ArmureModBlocks.PIERRE_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PIERRE_STAIRS = block(ArmureModBlocks.PIERRE_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PIERRE_SLAB = block(ArmureModBlocks.PIERRE_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PIERRE_FENCE = block(ArmureModBlocks.PIERRE_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PIERRE_FENCE_GATE = block(ArmureModBlocks.PIERRE_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PIERRE_PRESSURE_PLATE = block(ArmureModBlocks.PIERRE_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PIERRE_BUTTON = block(ArmureModBlocks.PIERRE_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NULLE_ORE = block(ArmureModBlocks.NULLE_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NULLE_BLOCK = block(ArmureModBlocks.NULLE_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NOIRE_ORE = block(ArmureModBlocks.NOIRE_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NOIRE_BLOCK = block(ArmureModBlocks.NOIRE_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NULLE = REGISTRY.register("nulle", () -> new NulleItem());
	public static final RegistryObject<Item> NOIRE = REGISTRY.register("noire", () -> new NoireItem());
	public static final RegistryObject<Item> SAND_PICKAXE = REGISTRY.register("sand_pickaxe", () -> new SandPickaxeItem());
	public static final RegistryObject<Item> SAND_AXE = REGISTRY.register("sand_axe", () -> new SandAxeItem());
	public static final RegistryObject<Item> SAND_SWORD = REGISTRY.register("sand_sword", () -> new SandSwordItem());
	public static final RegistryObject<Item> SAND_SHOVEL = REGISTRY.register("sand_shovel", () -> new SandShovelItem());
	public static final RegistryObject<Item> SAND_HOE = REGISTRY.register("sand_hoe", () -> new SandHoeItem());
	public static final RegistryObject<Item> CUIVRE_PICKAXE = REGISTRY.register("cuivre_pickaxe", () -> new CuivrePickaxeItem());
	public static final RegistryObject<Item> CUIVRE_AXE = REGISTRY.register("cuivre_axe", () -> new CuivreAxeItem());
	public static final RegistryObject<Item> CUIVRE_SWORD = REGISTRY.register("cuivre_sword", () -> new CuivreSwordItem());
	public static final RegistryObject<Item> CUIVRE_SHOVEL = REGISTRY.register("cuivre_shovel", () -> new CuivreShovelItem());
	public static final RegistryObject<Item> CUIVRE_HOE = REGISTRY.register("cuivre_hoe", () -> new CuivreHoeItem());
	public static final RegistryObject<Item> NULLE_PICKAXE = REGISTRY.register("nulle_pickaxe", () -> new NullePickaxeItem());
	public static final RegistryObject<Item> NULLE_AXE = REGISTRY.register("nulle_axe", () -> new NulleAxeItem());
	public static final RegistryObject<Item> NULLE_SWORD = REGISTRY.register("nulle_sword", () -> new NulleSwordItem());
	public static final RegistryObject<Item> NULLE_SHOVEL = REGISTRY.register("nulle_shovel", () -> new NulleShovelItem());
	public static final RegistryObject<Item> NULLE_HOE = REGISTRY.register("nulle_hoe", () -> new NulleHoeItem());
	public static final RegistryObject<Item> NOIRE_PICKAXE = REGISTRY.register("noire_pickaxe", () -> new NoirePickaxeItem());
	public static final RegistryObject<Item> NOIRE_AXE = REGISTRY.register("noire_axe", () -> new NoireAxeItem());
	public static final RegistryObject<Item> NOIRE_SWORD = REGISTRY.register("noire_sword", () -> new NoireSwordItem());
	public static final RegistryObject<Item> NOIRE_SHOVEL = REGISTRY.register("noire_shovel", () -> new NoireShovelItem());
	public static final RegistryObject<Item> NOIRE_HOE = REGISTRY.register("noire_hoe", () -> new NoireHoeItem());
	public static final RegistryObject<Item> BLANC_ARMOR_HELMET = REGISTRY.register("blanc_armor_helmet", () -> new BlancArmorItem.Helmet());
	public static final RegistryObject<Item> BLANC_ARMOR_CHESTPLATE = REGISTRY.register("blanc_armor_chestplate", () -> new BlancArmorItem.Chestplate());
	public static final RegistryObject<Item> BLANC_ARMOR_LEGGINGS = REGISTRY.register("blanc_armor_leggings", () -> new BlancArmorItem.Leggings());
	public static final RegistryObject<Item> BLANC_ARMOR_BOOTS = REGISTRY.register("blanc_armor_boots", () -> new BlancArmorItem.Boots());
	public static final RegistryObject<Item> OPALE_ARMOR_HELMET = REGISTRY.register("opale_armor_helmet", () -> new OpaleArmorItem.Helmet());
	public static final RegistryObject<Item> OPALE_ARMOR_CHESTPLATE = REGISTRY.register("opale_armor_chestplate", () -> new OpaleArmorItem.Chestplate());
	public static final RegistryObject<Item> OPALE_ARMOR_LEGGINGS = REGISTRY.register("opale_armor_leggings", () -> new OpaleArmorItem.Leggings());
	public static final RegistryObject<Item> OPALE_ARMOR_BOOTS = REGISTRY.register("opale_armor_boots", () -> new OpaleArmorItem.Boots());
	public static final RegistryObject<Item> GRIS_ARMOR_HELMET = REGISTRY.register("gris_armor_helmet", () -> new GrisArmorItem.Helmet());
	public static final RegistryObject<Item> GRIS_ARMOR_CHESTPLATE = REGISTRY.register("gris_armor_chestplate", () -> new GrisArmorItem.Chestplate());
	public static final RegistryObject<Item> GRIS_ARMOR_LEGGINGS = REGISTRY.register("gris_armor_leggings", () -> new GrisArmorItem.Leggings());
	public static final RegistryObject<Item> GRIS_ARMOR_BOOTS = REGISTRY.register("gris_armor_boots", () -> new GrisArmorItem.Boots());
	public static final RegistryObject<Item> BLANC_ORE = block(ArmureModBlocks.BLANC_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLANC_BLOCK = block(ArmureModBlocks.BLANC_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> OPALE_ORE = block(ArmureModBlocks.OPALE_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> OPALE_BLOCK = block(ArmureModBlocks.OPALE_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GRIS_ORE = block(ArmureModBlocks.GRIS_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GRIS_BLOCK = block(ArmureModBlocks.GRIS_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLANC = REGISTRY.register("blanc", () -> new BlancItem());
	public static final RegistryObject<Item> OPALE_DUST = REGISTRY.register("opale_dust", () -> new OpaleDustItem());
	public static final RegistryObject<Item> GRIS_INGOT = REGISTRY.register("gris_ingot", () -> new GrisIngotItem());
	public static final RegistryObject<Item> BLANC_PICKAXE = REGISTRY.register("blanc_pickaxe", () -> new BlancPickaxeItem());
	public static final RegistryObject<Item> BLANC_AXE = REGISTRY.register("blanc_axe", () -> new BlancAxeItem());
	public static final RegistryObject<Item> BLANC_SWORD = REGISTRY.register("blanc_sword", () -> new BlancSwordItem());
	public static final RegistryObject<Item> BLANC_SHOVEL = REGISTRY.register("blanc_shovel", () -> new BlancShovelItem());
	public static final RegistryObject<Item> BLANC_HOE = REGISTRY.register("blanc_hoe", () -> new BlancHoeItem());
	public static final RegistryObject<Item> OPALE_PICKAXE = REGISTRY.register("opale_pickaxe", () -> new OpalePickaxeItem());
	public static final RegistryObject<Item> OPALE_AXE = REGISTRY.register("opale_axe", () -> new OpaleAxeItem());
	public static final RegistryObject<Item> OPALE_SWORD = REGISTRY.register("opale_sword", () -> new OpaleSwordItem());
	public static final RegistryObject<Item> OPALE_SHOVEL = REGISTRY.register("opale_shovel", () -> new OpaleShovelItem());
	public static final RegistryObject<Item> OPALE_HOE = REGISTRY.register("opale_hoe", () -> new OpaleHoeItem());
	public static final RegistryObject<Item> GRIS_PICKAXE = REGISTRY.register("gris_pickaxe", () -> new GrisPickaxeItem());
	public static final RegistryObject<Item> GRIS_AXE = REGISTRY.register("gris_axe", () -> new GrisAxeItem());
	public static final RegistryObject<Item> GRIS_SWORD = REGISTRY.register("gris_sword", () -> new GrisSwordItem());
	public static final RegistryObject<Item> GRIS_SHOVEL = REGISTRY.register("gris_shovel", () -> new GrisShovelItem());
	public static final RegistryObject<Item> GRIS_HOE = REGISTRY.register("gris_hoe", () -> new GrisHoeItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
